# demo-service-deployment-service-ingress.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
        - name: comment-service
          image: comment-service
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: comment-service
#spec:
#  selector:
#    app: comment-service
#  ports:
#    - protocol: TCP
#      port: 8080 # The port that the service is running on in the cluster
#  type: LoadBalancer # type of the service.
